### ISSUE TITLE
Use profiles in docker-compose to disable webserver.

### ISSUE THREAD

**Issue by bmschmidt** [senderle/bookworm-compose#20]
New in docker-compose 3.9: https://docs.docker.com/compose/profiles/.

Now that this stack is working, I'm trying deploying some of my higher-traffic bookworms from inside the cloud rather than have them broken all the time.

Since I have Apache webhosting set up there already, I have no need for the nginx server in this stack.

So adding to docker-compose this:

```
  nginx:
    [...]
    depends_on:
      - mariadb
      - bookworm
    profiles:
      -	webserver
```

and running `docker-compose up` will not start the webserver by default, only the API.

This will also be a nice way to handle traefik. 

There will still be questions about what are the sensible *default* profiles to use.
